package com.fifty.fixitnow.core.util

sealed class Screen(val route: String) {
    object AuthScreen : Screen("auth_screen")
    object OnBoardingScreen : Screen("on_boarding_screen")
    object SelectCountryScreen : Screen("select_country_screen")
    object OtpVerificationScreen : Screen("otp_verification_screen")
    object UserDashboardScreen : Screen("user_dashboard_screen")
    object WorkerDashboardScreen : Screen("worker_dashboard_screen")
    object FavoriteScreen : Screen("favorite_screen")
    object HistoryScreen : Screen("work_history_screen")
    object NotificationScreen : Screen("notification_screen")
    object SearchCategoryScreen : Screen("search_category_screen")
    object WorkerListScreen : Screen("worker_list_screen")
    object WorkerProfileScreen : Screen("worker_profile_screen")
    object ReviewAndRatingScreen : Screen("rating_and_review_screen")
    object RegisterAsWorkerScreen : Screen("register_as_worker_screen")
    object ChatScreen : Screen("chat_screen")
    object MessageScreen : Screen("message_screen")
    object SelectLocationScreen : Screen("select_location_screen")
    object DetectCurrentLocationScreen : Screen("detect_current_location_screen")
    object UserProfileScreen : Screen("user_profile_screen")
    object UpdateUserProfileScreen : Screen("update_user_profile_screen")
    object SettingsScreen : Screen("settings_screen")
    object TermsAndConditionScreen : Screen("terms_and_condition_screen")
    object ContactUsScreen : Screen("contact_us_screen")
    object PrivacyPolicyScreen : Screen("privacy_policy_screen")
    object SearchWorkerScreen : Screen("search_worker_screen")
    object PostSampleWorkScreen : Screen("post_sample_work_screen")
    object WorkProposalScreen : Screen("work_proposal_screen")
}
